### ISSUE TITLE
License of annotations

### ISSUE THREAD

**Issue by annefriedrich** [elsevierlabs/OA-STM-Corpus#5]
Dear Elsevier team,
thanks a lot for making this great resource available.
I understand the texts are licensed under CC-BY, but I cannot really tell from the Readme under which license the annotations available in this repo are licensed. I would appreciate very much if you could add an appropriate license.
Thanks a lot.
Best Regards,
Anne

**Comment by rdaniel** [comment]
The annotations are also CC-BY. We will add such a statement.

Sent from my iPhone

On Jan 30, 2020, at 7:25 AM, annefriedrich <notifications@github.com<mailto:notifications@github.com>> wrote:


*** External email: use caution ***



Dear Elsevier team,
thanks a lot for making this great resource available.
I understand the texts are licensed under CC-BY, but I cannot really tell from the Readme under which license the annotations available in this repo are licensed. I would appreciate very much if you could add an appropriate license.
Thanks a lot.
Best Regards,
Anne

**Comment by annefriedrich** [comment]
Thanks a lot!
